version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - durationcheck
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - mirror
    - misspell
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - testifylint
    - unconvert
    - unused
    - wastedassign
  settings:
    gocritic:
      disabled-checks:
        - hugeParam
        - ifElseChain
        - ptrToRefParam
        - dupImport
        - uncheckedInlineErr
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      disable:
        - fieldalignment
        - deepequalerrors
      enable-all: true
    revive:
      enable-all-rules: false
      rules:
        - name: superfluous-else
        - name: exported
    testifylint:
      disable-all: true
      enable:
        - nil-compare
        - compares
        - error-is-as
        - bool-compare
        - empty
        - len
        - expected-actual
        - error-nil
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
