---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--strict, -c=.yamllint.yaml]
        entry: yamllint
        files: \.ya?ml$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        name: markdownlint
        description: "Checks the style of Markdown/Commonmark files."
        entry: ghcr.io/igorshubovych/markdownlint-cli
        language: docker_image
        types: [markdown]
        minimum_pre_commit_version: 0.15.0
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        args: [hadolint, --config, .hadolint.yaml]
        description: Runs hadolint to lint Dockerfiles
        language: docker_image
        types: ["dockerfile"]
        entry: hadolint/hadolint:v2.12.0-alpine
  - repo: local
    hooks:
      - id: goimports-nvidia
        name: goimports-nvidia
        description: run goimports
        entry: goimports -w -local nvidia.com/NVIDIA/go-dcgm
        language: golang
        types: [go]
        exclude: '(\.pb|\.sql|mock_.*)\.go'
      - id: go-mod-tidy
        name: 'go-mod-tidy'
        entry: scripts/lint/go-mod-tidy.sh
        pass_filenames: false
        language: 'script'
        description: "Runs `go mod tidy -v`, requires golang"
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
      - id: golangci-lint-config-verify
        name: golangci-lint-config-verify
        description: Verifies the configuration file
        entry: golangci-lint config verify
        files: .golangci.yml
        language: golang
        pass_filenames: false
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go.
        entry: golangci-lint run --new-from-rev origin/main --fix --allow-parallel-runners --timeout 5m
        types: [go]
        language: golang
        require_serial: true
        pass_filenames: false
