// Code generated by MockGen. DO NOT EDIT.
// Source: native_calls.go
//
// Generated by this command:
//
//	mockgen -source=native_calls.go -destination=native_calls_mock_test.go -package=dcgm -mock_names=sessionCalls=MockSessionCalls,watchGroupOps=MockWatchGroupOps,pidWatchOps=MockPIDWatchOps,deviceStatusOps=MockDeviceStatusOps,healthGroupOps=MockHealthGroupOps,policyRegistrationCalls=MockPolicyRegistrationCalls,fieldPolicyListCalls=MockFieldPolicyListCalls,fieldPolicyEventCalls=MockFieldPolicyEventCalls,multiNodeDiagnosticCalls=MockMultiNodeDiagnosticCalls,deviceInfoOps=MockDeviceInfoOps,policyReadOps=MockPolicyReadOps,topologyOps=MockTopologyOps
//

// Package dcgm is a generated GoMock package.
package dcgm

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionCalls is a mock of sessionCalls interface.
type MockSessionCalls struct {
	ctrl     *gomock.Controller
	recorder *MockSessionCallsMockRecorder
	isgomock struct{}
}

// MockSessionCallsMockRecorder is the mock recorder for MockSessionCalls.
type MockSessionCallsMockRecorder struct {
	mock *MockSessionCalls
}

// NewMockSessionCalls creates a new mock instance.
func NewMockSessionCalls(ctrl *gomock.Controller) *MockSessionCalls {
	mock := &MockSessionCalls{ctrl: ctrl}
	mock.recorder = &MockSessionCallsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionCalls) EXPECT() *MockSessionCallsMockRecorder {
	return m.recorder
}

// closeLibrary mocks base method.
func (m *MockSessionCalls) closeLibrary() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "closeLibrary")
}

// closeLibrary indicates an expected call of closeLibrary.
func (mr *MockSessionCallsMockRecorder) closeLibrary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "closeLibrary", reflect.TypeOf((*MockSessionCalls)(nil).closeLibrary))
}

// connectStandalone mocks base method.
func (m *MockSessionCalls) connectStandalone(arg0 ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "connectStandalone", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// connectStandalone indicates an expected call of connectStandalone.
func (mr *MockSessionCallsMockRecorder) connectStandalone(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "connectStandalone", reflect.TypeOf((*MockSessionCalls)(nil).connectStandalone), arg0...)
}

// disconnectStandalone mocks base method.
func (m *MockSessionCalls) disconnectStandalone() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "disconnectStandalone")
	ret0, _ := ret[0].(error)
	return ret0
}

// disconnectStandalone indicates an expected call of disconnectStandalone.
func (mr *MockSessionCallsMockRecorder) disconnectStandalone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "disconnectStandalone", reflect.TypeOf((*MockSessionCalls)(nil).disconnectStandalone))
}

// loadLibrary mocks base method.
func (m *MockSessionCalls) loadLibrary() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "loadLibrary")
	ret0, _ := ret[0].(error)
	return ret0
}

// loadLibrary indicates an expected call of loadLibrary.
func (mr *MockSessionCallsMockRecorder) loadLibrary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "loadLibrary", reflect.TypeOf((*MockSessionCalls)(nil).loadLibrary))
}

// startEmbedded mocks base method.
func (m *MockSessionCalls) startEmbedded() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "startEmbedded")
	ret0, _ := ret[0].(error)
	return ret0
}

// startEmbedded indicates an expected call of startEmbedded.
func (mr *MockSessionCallsMockRecorder) startEmbedded() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "startEmbedded", reflect.TypeOf((*MockSessionCalls)(nil).startEmbedded))
}

// startHostengine mocks base method.
func (m *MockSessionCalls) startHostengine() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "startHostengine")
	ret0, _ := ret[0].(error)
	return ret0
}

// startHostengine indicates an expected call of startHostengine.
func (mr *MockSessionCallsMockRecorder) startHostengine() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "startHostengine", reflect.TypeOf((*MockSessionCalls)(nil).startHostengine))
}

// stopEmbedded mocks base method.
func (m *MockSessionCalls) stopEmbedded() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "stopEmbedded")
	ret0, _ := ret[0].(error)
	return ret0
}

// stopEmbedded indicates an expected call of stopEmbedded.
func (mr *MockSessionCallsMockRecorder) stopEmbedded() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "stopEmbedded", reflect.TypeOf((*MockSessionCalls)(nil).stopEmbedded))
}

// stopHostengine mocks base method.
func (m *MockSessionCalls) stopHostengine() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "stopHostengine")
	ret0, _ := ret[0].(error)
	return ret0
}

// stopHostengine indicates an expected call of stopHostengine.
func (mr *MockSessionCallsMockRecorder) stopHostengine() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "stopHostengine", reflect.TypeOf((*MockSessionCalls)(nil).stopHostengine))
}

// MockWatchGroupOps is a mock of watchGroupOps interface.
type MockWatchGroupOps struct {
	ctrl     *gomock.Controller
	recorder *MockWatchGroupOpsMockRecorder
	isgomock struct{}
}

// MockWatchGroupOpsMockRecorder is the mock recorder for MockWatchGroupOps.
type MockWatchGroupOpsMockRecorder struct {
	mock *MockWatchGroupOps
}

// NewMockWatchGroupOps creates a new mock instance.
func NewMockWatchGroupOps(ctrl *gomock.Controller) *MockWatchGroupOps {
	mock := &MockWatchGroupOps{ctrl: ctrl}
	mock.recorder = &MockWatchGroupOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatchGroupOps) EXPECT() *MockWatchGroupOpsMockRecorder {
	return m.recorder
}

// addToGroup mocks base method.
func (m *MockWatchGroupOps) addToGroup(arg0 GroupHandle, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "addToGroup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// addToGroup indicates an expected call of addToGroup.
func (mr *MockWatchGroupOpsMockRecorder) addToGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "addToGroup", reflect.TypeOf((*MockWatchGroupOps)(nil).addToGroup), arg0, arg1)
}

// createGroup mocks base method.
func (m *MockWatchGroupOps) createGroup(arg0 string, arg1 bool) (GroupHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "createGroup", arg0, arg1)
	ret0, _ := ret[0].(GroupHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// createGroup indicates an expected call of createGroup.
func (mr *MockWatchGroupOpsMockRecorder) createGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createGroup", reflect.TypeOf((*MockWatchGroupOps)(nil).createGroup), arg0, arg1)
}

// destroyGroup mocks base method.
func (m *MockWatchGroupOps) destroyGroup(arg0 GroupHandle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "destroyGroup", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// destroyGroup indicates an expected call of destroyGroup.
func (mr *MockWatchGroupOpsMockRecorder) destroyGroup(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "destroyGroup", reflect.TypeOf((*MockWatchGroupOps)(nil).destroyGroup), arg0)
}

// updateAllFields mocks base method.
func (m *MockWatchGroupOps) updateAllFields() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "updateAllFields")
	ret0, _ := ret[0].(error)
	return ret0
}

// updateAllFields indicates an expected call of updateAllFields.
func (mr *MockWatchGroupOpsMockRecorder) updateAllFields() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "updateAllFields", reflect.TypeOf((*MockWatchGroupOps)(nil).updateAllFields))
}

// watchFieldsNative mocks base method.
func (m *MockWatchGroupOps) watchFieldsNative(arg0 FieldHandle, arg1 GroupHandle, arg2 int64, arg3 float64, arg4 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "watchFieldsNative", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// watchFieldsNative indicates an expected call of watchFieldsNative.
func (mr *MockWatchGroupOpsMockRecorder) watchFieldsNative(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "watchFieldsNative", reflect.TypeOf((*MockWatchGroupOps)(nil).watchFieldsNative), arg0, arg1, arg2, arg3, arg4)
}

// MockPIDWatchOps is a mock of pidWatchOps interface.
type MockPIDWatchOps struct {
	ctrl     *gomock.Controller
	recorder *MockPIDWatchOpsMockRecorder
	isgomock struct{}
}

// MockPIDWatchOpsMockRecorder is the mock recorder for MockPIDWatchOps.
type MockPIDWatchOpsMockRecorder struct {
	mock *MockPIDWatchOps
}

// NewMockPIDWatchOps creates a new mock instance.
func NewMockPIDWatchOps(ctrl *gomock.Controller) *MockPIDWatchOps {
	mock := &MockPIDWatchOps{ctrl: ctrl}
	mock.recorder = &MockPIDWatchOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPIDWatchOps) EXPECT() *MockPIDWatchOpsMockRecorder {
	return m.recorder
}

// addToGroup mocks base method.
func (m *MockPIDWatchOps) addToGroup(arg0 GroupHandle, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "addToGroup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// addToGroup indicates an expected call of addToGroup.
func (mr *MockPIDWatchOpsMockRecorder) addToGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "addToGroup", reflect.TypeOf((*MockPIDWatchOps)(nil).addToGroup), arg0, arg1)
}

// createGroup mocks base method.
func (m *MockPIDWatchOps) createGroup(arg0 string, arg1 bool) (GroupHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "createGroup", arg0, arg1)
	ret0, _ := ret[0].(GroupHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// createGroup indicates an expected call of createGroup.
func (mr *MockPIDWatchOpsMockRecorder) createGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createGroup", reflect.TypeOf((*MockPIDWatchOps)(nil).createGroup), arg0, arg1)
}

// destroyGroup mocks base method.
func (m *MockPIDWatchOps) destroyGroup(arg0 GroupHandle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "destroyGroup", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// destroyGroup indicates an expected call of destroyGroup.
func (mr *MockPIDWatchOpsMockRecorder) destroyGroup(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "destroyGroup", reflect.TypeOf((*MockPIDWatchOps)(nil).destroyGroup), arg0)
}

// getSupportedDevices mocks base method.
func (m *MockPIDWatchOps) getSupportedDevices() ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getSupportedDevices")
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getSupportedDevices indicates an expected call of getSupportedDevices.
func (mr *MockPIDWatchOpsMockRecorder) getSupportedDevices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getSupportedDevices", reflect.TypeOf((*MockPIDWatchOps)(nil).getSupportedDevices))
}

// updateAllFields mocks base method.
func (m *MockPIDWatchOps) updateAllFields() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "updateAllFields")
	ret0, _ := ret[0].(error)
	return ret0
}

// updateAllFields indicates an expected call of updateAllFields.
func (mr *MockPIDWatchOpsMockRecorder) updateAllFields() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "updateAllFields", reflect.TypeOf((*MockPIDWatchOps)(nil).updateAllFields))
}

// watchPidFieldsNative mocks base method.
func (m *MockPIDWatchOps) watchPidFieldsNative(arg0 GroupHandle, arg1, arg2 time.Duration, arg3 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "watchPidFieldsNative", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// watchPidFieldsNative indicates an expected call of watchPidFieldsNative.
func (mr *MockPIDWatchOpsMockRecorder) watchPidFieldsNative(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "watchPidFieldsNative", reflect.TypeOf((*MockPIDWatchOps)(nil).watchPidFieldsNative), arg0, arg1, arg2, arg3)
}

// MockDeviceStatusOps is a mock of deviceStatusOps interface.
type MockDeviceStatusOps struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceStatusOpsMockRecorder
	isgomock struct{}
}

// MockDeviceStatusOpsMockRecorder is the mock recorder for MockDeviceStatusOps.
type MockDeviceStatusOpsMockRecorder struct {
	mock *MockDeviceStatusOps
}

// NewMockDeviceStatusOps creates a new mock instance.
func NewMockDeviceStatusOps(ctrl *gomock.Controller) *MockDeviceStatusOps {
	mock := &MockDeviceStatusOps{ctrl: ctrl}
	mock.recorder = &MockDeviceStatusOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceStatusOps) EXPECT() *MockDeviceStatusOpsMockRecorder {
	return m.recorder
}

// destroyGroup mocks base method.
func (m *MockDeviceStatusOps) destroyGroup(arg0 GroupHandle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "destroyGroup", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// destroyGroup indicates an expected call of destroyGroup.
func (mr *MockDeviceStatusOpsMockRecorder) destroyGroup(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "destroyGroup", reflect.TypeOf((*MockDeviceStatusOps)(nil).destroyGroup), arg0)
}

// fieldGroupCreate mocks base method.
func (m *MockDeviceStatusOps) fieldGroupCreate(arg0 string, arg1 []Short) (FieldHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "fieldGroupCreate", arg0, arg1)
	ret0, _ := ret[0].(FieldHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// fieldGroupCreate indicates an expected call of fieldGroupCreate.
func (mr *MockDeviceStatusOpsMockRecorder) fieldGroupCreate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "fieldGroupCreate", reflect.TypeOf((*MockDeviceStatusOps)(nil).fieldGroupCreate), arg0, arg1)
}

// fieldGroupDestroy mocks base method.
func (m *MockDeviceStatusOps) fieldGroupDestroy(arg0 FieldHandle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "fieldGroupDestroy", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// fieldGroupDestroy indicates an expected call of fieldGroupDestroy.
func (mr *MockDeviceStatusOpsMockRecorder) fieldGroupDestroy(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "fieldGroupDestroy", reflect.TypeOf((*MockDeviceStatusOps)(nil).fieldGroupDestroy), arg0)
}

// getLatestValuesForFields mocks base method.
func (m *MockDeviceStatusOps) getLatestValuesForFields(arg0 uint, arg1 []Short) ([]FieldValue_v1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getLatestValuesForFields", arg0, arg1)
	ret0, _ := ret[0].([]FieldValue_v1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getLatestValuesForFields indicates an expected call of getLatestValuesForFields.
func (mr *MockDeviceStatusOpsMockRecorder) getLatestValuesForFields(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getLatestValuesForFields", reflect.TypeOf((*MockDeviceStatusOps)(nil).getLatestValuesForFields), arg0, arg1)
}

// watchFields mocks base method.
func (m *MockDeviceStatusOps) watchFields(arg0 uint, arg1 FieldHandle, arg2 string) (GroupHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "watchFields", arg0, arg1, arg2)
	ret0, _ := ret[0].(GroupHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// watchFields indicates an expected call of watchFields.
func (mr *MockDeviceStatusOpsMockRecorder) watchFields(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "watchFields", reflect.TypeOf((*MockDeviceStatusOps)(nil).watchFields), arg0, arg1, arg2)
}

// MockHealthGroupOps is a mock of healthGroupOps interface.
type MockHealthGroupOps struct {
	ctrl     *gomock.Controller
	recorder *MockHealthGroupOpsMockRecorder
	isgomock struct{}
}

// MockHealthGroupOpsMockRecorder is the mock recorder for MockHealthGroupOps.
type MockHealthGroupOpsMockRecorder struct {
	mock *MockHealthGroupOps
}

// NewMockHealthGroupOps creates a new mock instance.
func NewMockHealthGroupOps(ctrl *gomock.Controller) *MockHealthGroupOps {
	mock := &MockHealthGroupOps{ctrl: ctrl}
	mock.recorder = &MockHealthGroupOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthGroupOps) EXPECT() *MockHealthGroupOpsMockRecorder {
	return m.recorder
}

// addToGroup mocks base method.
func (m *MockHealthGroupOps) addToGroup(arg0 GroupHandle, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "addToGroup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// addToGroup indicates an expected call of addToGroup.
func (mr *MockHealthGroupOpsMockRecorder) addToGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "addToGroup", reflect.TypeOf((*MockHealthGroupOps)(nil).addToGroup), arg0, arg1)
}

// createGroup mocks base method.
func (m *MockHealthGroupOps) createGroup(arg0 string, arg1 bool) (GroupHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "createGroup", arg0, arg1)
	ret0, _ := ret[0].(GroupHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// createGroup indicates an expected call of createGroup.
func (mr *MockHealthGroupOpsMockRecorder) createGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "createGroup", reflect.TypeOf((*MockHealthGroupOps)(nil).createGroup), arg0, arg1)
}

// destroyGroup mocks base method.
func (m *MockHealthGroupOps) destroyGroup(arg0 GroupHandle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "destroyGroup", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// destroyGroup indicates an expected call of destroyGroup.
func (mr *MockHealthGroupOpsMockRecorder) destroyGroup(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "destroyGroup", reflect.TypeOf((*MockHealthGroupOps)(nil).destroyGroup), arg0)
}

// healthCheck mocks base method.
func (m *MockHealthGroupOps) healthCheck(arg0 GroupHandle) (HealthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "healthCheck", arg0)
	ret0, _ := ret[0].(HealthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// healthCheck indicates an expected call of healthCheck.
func (mr *MockHealthGroupOpsMockRecorder) healthCheck(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "healthCheck", reflect.TypeOf((*MockHealthGroupOps)(nil).healthCheck), arg0)
}

// healthSet mocks base method.
func (m *MockHealthGroupOps) healthSet(arg0 GroupHandle, arg1 HealthSystem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "healthSet", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// healthSet indicates an expected call of healthSet.
func (mr *MockHealthGroupOpsMockRecorder) healthSet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "healthSet", reflect.TypeOf((*MockHealthGroupOps)(nil).healthSet), arg0, arg1)
}

// MockPolicyRegistrationCalls is a mock of policyRegistrationCalls interface.
type MockPolicyRegistrationCalls struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyRegistrationCallsMockRecorder
	isgomock struct{}
}

// MockPolicyRegistrationCallsMockRecorder is the mock recorder for MockPolicyRegistrationCalls.
type MockPolicyRegistrationCallsMockRecorder struct {
	mock *MockPolicyRegistrationCalls
}

// NewMockPolicyRegistrationCalls creates a new mock instance.
func NewMockPolicyRegistrationCalls(ctrl *gomock.Controller) *MockPolicyRegistrationCalls {
	mock := &MockPolicyRegistrationCalls{ctrl: ctrl}
	mock.recorder = &MockPolicyRegistrationCallsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyRegistrationCalls) EXPECT() *MockPolicyRegistrationCallsMockRecorder {
	return m.recorder
}

// registerPolicyNative mocks base method.
func (m *MockPolicyRegistrationCalls) registerPolicyNative(arg0 GroupHandle, arg1 uint32, arg2 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "registerPolicyNative", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// registerPolicyNative indicates an expected call of registerPolicyNative.
func (mr *MockPolicyRegistrationCallsMockRecorder) registerPolicyNative(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "registerPolicyNative", reflect.TypeOf((*MockPolicyRegistrationCalls)(nil).registerPolicyNative), arg0, arg1, arg2)
}

// unregisterPolicyNative mocks base method.
func (m *MockPolicyRegistrationCalls) unregisterPolicyNative(arg0 GroupHandle, arg1 uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "unregisterPolicyNative", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// unregisterPolicyNative indicates an expected call of unregisterPolicyNative.
func (mr *MockPolicyRegistrationCallsMockRecorder) unregisterPolicyNative(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "unregisterPolicyNative", reflect.TypeOf((*MockPolicyRegistrationCalls)(nil).unregisterPolicyNative), arg0, arg1)
}

// MockFieldPolicyListCalls is a mock of fieldPolicyListCalls interface.
type MockFieldPolicyListCalls struct {
	ctrl     *gomock.Controller
	recorder *MockFieldPolicyListCallsMockRecorder
	isgomock struct{}
}

// MockFieldPolicyListCallsMockRecorder is the mock recorder for MockFieldPolicyListCalls.
type MockFieldPolicyListCallsMockRecorder struct {
	mock *MockFieldPolicyListCalls
}

// NewMockFieldPolicyListCalls creates a new mock instance.
func NewMockFieldPolicyListCalls(ctrl *gomock.Controller) *MockFieldPolicyListCalls {
	mock := &MockFieldPolicyListCalls{ctrl: ctrl}
	mock.recorder = &MockFieldPolicyListCallsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFieldPolicyListCalls) EXPECT() *MockFieldPolicyListCallsMockRecorder {
	return m.recorder
}

// fieldPolicyCount mocks base method.
func (m *MockFieldPolicyListCalls) fieldPolicyCount() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "fieldPolicyCount")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// fieldPolicyCount indicates an expected call of fieldPolicyCount.
func (mr *MockFieldPolicyListCallsMockRecorder) fieldPolicyCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "fieldPolicyCount", reflect.TypeOf((*MockFieldPolicyListCalls)(nil).fieldPolicyCount))
}

// fieldPolicyList mocks base method.
func (m *MockFieldPolicyListCalls) fieldPolicyList(arg0 int) ([]FieldPolicy, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "fieldPolicyList", arg0)
	ret0, _ := ret[0].([]FieldPolicy)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// fieldPolicyList indicates an expected call of fieldPolicyList.
func (mr *MockFieldPolicyListCallsMockRecorder) fieldPolicyList(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "fieldPolicyList", reflect.TypeOf((*MockFieldPolicyListCalls)(nil).fieldPolicyList), arg0)
}

// MockFieldPolicyEventCalls is a mock of fieldPolicyEventCalls interface.
type MockFieldPolicyEventCalls struct {
	ctrl     *gomock.Controller
	recorder *MockFieldPolicyEventCallsMockRecorder
	isgomock struct{}
}

// MockFieldPolicyEventCallsMockRecorder is the mock recorder for MockFieldPolicyEventCalls.
type MockFieldPolicyEventCallsMockRecorder struct {
	mock *MockFieldPolicyEventCalls
}

// NewMockFieldPolicyEventCalls creates a new mock instance.
func NewMockFieldPolicyEventCalls(ctrl *gomock.Controller) *MockFieldPolicyEventCalls {
	mock := &MockFieldPolicyEventCalls{ctrl: ctrl}
	mock.recorder = &MockFieldPolicyEventCallsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFieldPolicyEventCalls) EXPECT() *MockFieldPolicyEventCallsMockRecorder {
	return m.recorder
}

// registerFieldPolicyNative mocks base method.
func (m *MockFieldPolicyEventCalls) registerFieldPolicyNative(arg0 Short, arg1, arg2 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "registerFieldPolicyNative", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// registerFieldPolicyNative indicates an expected call of registerFieldPolicyNative.
func (mr *MockFieldPolicyEventCallsMockRecorder) registerFieldPolicyNative(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "registerFieldPolicyNative", reflect.TypeOf((*MockFieldPolicyEventCalls)(nil).registerFieldPolicyNative), arg0, arg1, arg2)
}

// unregisterFieldPolicyNative mocks base method.
func (m *MockFieldPolicyEventCalls) unregisterFieldPolicyNative(arg0 Short, arg1 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "unregisterFieldPolicyNative", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// unregisterFieldPolicyNative indicates an expected call of unregisterFieldPolicyNative.
func (mr *MockFieldPolicyEventCallsMockRecorder) unregisterFieldPolicyNative(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "unregisterFieldPolicyNative", reflect.TypeOf((*MockFieldPolicyEventCalls)(nil).unregisterFieldPolicyNative), arg0, arg1)
}

// MockMultiNodeDiagnosticCalls is a mock of multiNodeDiagnosticCalls interface.
type MockMultiNodeDiagnosticCalls struct {
	ctrl     *gomock.Controller
	recorder *MockMultiNodeDiagnosticCallsMockRecorder
	isgomock struct{}
}

// MockMultiNodeDiagnosticCallsMockRecorder is the mock recorder for MockMultiNodeDiagnosticCalls.
type MockMultiNodeDiagnosticCallsMockRecorder struct {
	mock *MockMultiNodeDiagnosticCalls
}

// NewMockMultiNodeDiagnosticCalls creates a new mock instance.
func NewMockMultiNodeDiagnosticCalls(ctrl *gomock.Controller) *MockMultiNodeDiagnosticCalls {
	mock := &MockMultiNodeDiagnosticCalls{ctrl: ctrl}
	mock.recorder = &MockMultiNodeDiagnosticCallsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMultiNodeDiagnosticCalls) EXPECT() *MockMultiNodeDiagnosticCallsMockRecorder {
	return m.recorder
}

// runMultiNodeDiagnosticNative mocks base method.
func (m *MockMultiNodeDiagnosticCalls) runMultiNodeDiagnosticNative(arg0 MultiNodeDiagnosticRequest) (MultiNodeDiagnosticResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "runMultiNodeDiagnosticNative", arg0)
	ret0, _ := ret[0].(MultiNodeDiagnosticResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// runMultiNodeDiagnosticNative indicates an expected call of runMultiNodeDiagnosticNative.
func (mr *MockMultiNodeDiagnosticCallsMockRecorder) runMultiNodeDiagnosticNative(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "runMultiNodeDiagnosticNative", reflect.TypeOf((*MockMultiNodeDiagnosticCalls)(nil).runMultiNodeDiagnosticNative), arg0)
}

// stopMultiNodeDiagnosticNative mocks base method.
func (m *MockMultiNodeDiagnosticCalls) stopMultiNodeDiagnosticNative() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "stopMultiNodeDiagnosticNative")
	ret0, _ := ret[0].(error)
	return ret0
}

// stopMultiNodeDiagnosticNative indicates an expected call of stopMultiNodeDiagnosticNative.
func (mr *MockMultiNodeDiagnosticCallsMockRecorder) stopMultiNodeDiagnosticNative() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "stopMultiNodeDiagnosticNative", reflect.TypeOf((*MockMultiNodeDiagnosticCalls)(nil).stopMultiNodeDiagnosticNative))
}

// MockDeviceInfoOps is a mock of deviceInfoOps interface.
type MockDeviceInfoOps struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceInfoOpsMockRecorder
	isgomock struct{}
}

// MockDeviceInfoOpsMockRecorder is the mock recorder for MockDeviceInfoOps.
type MockDeviceInfoOpsMockRecorder struct {
	mock *MockDeviceInfoOps
}

// NewMockDeviceInfoOps creates a new mock instance.
func NewMockDeviceInfoOps(ctrl *gomock.Controller) *MockDeviceInfoOps {
	mock := &MockDeviceInfoOps{ctrl: ctrl}
	mock.recorder = &MockDeviceInfoOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceInfoOps) EXPECT() *MockDeviceInfoOpsMockRecorder {
	return m.recorder
}

// getCPUAffinity mocks base method.
func (m *MockDeviceInfoOps) getCPUAffinity(arg0 uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getCPUAffinity", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getCPUAffinity indicates an expected call of getCPUAffinity.
func (mr *MockDeviceInfoOpsMockRecorder) getCPUAffinity(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getCPUAffinity", reflect.TypeOf((*MockDeviceInfoOps)(nil).getCPUAffinity), arg0)
}

// getDeviceTopology mocks base method.
func (m *MockDeviceInfoOps) getDeviceTopology(arg0 uint) ([]P2PLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getDeviceTopology", arg0)
	ret0, _ := ret[0].([]P2PLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getDeviceTopology indicates an expected call of getDeviceTopology.
func (mr *MockDeviceInfoOpsMockRecorder) getDeviceTopology(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getDeviceTopology", reflect.TypeOf((*MockDeviceInfoOps)(nil).getDeviceTopology), arg0)
}

// getGPUStatus mocks base method.
func (m *MockDeviceInfoOps) getGPUStatus(arg0 uint) EntityStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getGPUStatus", arg0)
	ret0, _ := ret[0].(EntityStatus)
	return ret0
}

// getGPUStatus indicates an expected call of getGPUStatus.
func (mr *MockDeviceInfoOpsMockRecorder) getGPUStatus(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getGPUStatus", reflect.TypeOf((*MockDeviceInfoOps)(nil).getGPUStatus), arg0)
}

// getPciBandwidth mocks base method.
func (m *MockDeviceInfoOps) getPciBandwidth(arg0 uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getPciBandwidth", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getPciBandwidth indicates an expected call of getPciBandwidth.
func (mr *MockDeviceInfoOpsMockRecorder) getPciBandwidth(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getPciBandwidth", reflect.TypeOf((*MockDeviceInfoOps)(nil).getPciBandwidth), arg0)
}

// getSupportedDevices mocks base method.
func (m *MockDeviceInfoOps) getSupportedDevices() ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getSupportedDevices")
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getSupportedDevices indicates an expected call of getSupportedDevices.
func (mr *MockDeviceInfoOpsMockRecorder) getSupportedDevices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getSupportedDevices", reflect.TypeOf((*MockDeviceInfoOps)(nil).getSupportedDevices))
}

// readDeviceAttributes mocks base method.
func (m *MockDeviceInfoOps) readDeviceAttributes(arg0 uint) (deviceAttributes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "readDeviceAttributes", arg0)
	ret0, _ := ret[0].(deviceAttributes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// readDeviceAttributes indicates an expected call of readDeviceAttributes.
func (mr *MockDeviceInfoOpsMockRecorder) readDeviceAttributes(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "readDeviceAttributes", reflect.TypeOf((*MockDeviceInfoOps)(nil).readDeviceAttributes), arg0)
}

// MockPolicyReadOps is a mock of policyReadOps interface.
type MockPolicyReadOps struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyReadOpsMockRecorder
	isgomock struct{}
}

// MockPolicyReadOpsMockRecorder is the mock recorder for MockPolicyReadOps.
type MockPolicyReadOpsMockRecorder struct {
	mock *MockPolicyReadOps
}

// NewMockPolicyReadOps creates a new mock instance.
func NewMockPolicyReadOps(ctrl *gomock.Controller) *MockPolicyReadOps {
	mock := &MockPolicyReadOps{ctrl: ctrl}
	mock.recorder = &MockPolicyReadOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyReadOps) EXPECT() *MockPolicyReadOpsMockRecorder {
	return m.recorder
}

// getGroupInfo mocks base method.
func (m *MockPolicyReadOps) getGroupInfo(arg0 GroupHandle) (*GroupInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getGroupInfo", arg0)
	ret0, _ := ret[0].(*GroupInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getGroupInfo indicates an expected call of getGroupInfo.
func (mr *MockPolicyReadOpsMockRecorder) getGroupInfo(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getGroupInfo", reflect.TypeOf((*MockPolicyReadOps)(nil).getGroupInfo), arg0)
}

// readPolicy mocks base method.
func (m *MockPolicyReadOps) readPolicy(arg0 GroupHandle, arg1 int) (policySnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "readPolicy", arg0, arg1)
	ret0, _ := ret[0].(policySnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// readPolicy indicates an expected call of readPolicy.
func (mr *MockPolicyReadOpsMockRecorder) readPolicy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "readPolicy", reflect.TypeOf((*MockPolicyReadOps)(nil).readPolicy), arg0, arg1)
}

// MockTopologyOps is a mock of topologyOps interface.
type MockTopologyOps struct {
	ctrl     *gomock.Controller
	recorder *MockTopologyOpsMockRecorder
	isgomock struct{}
}

// MockTopologyOpsMockRecorder is the mock recorder for MockTopologyOps.
type MockTopologyOpsMockRecorder struct {
	mock *MockTopologyOps
}

// NewMockTopologyOps creates a new mock instance.
func NewMockTopologyOps(ctrl *gomock.Controller) *MockTopologyOps {
	mock := &MockTopologyOps{ctrl: ctrl}
	mock.recorder = &MockTopologyOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopologyOps) EXPECT() *MockTopologyOpsMockRecorder {
	return m.recorder
}

// entitiesGetLatestValues mocks base method.
func (m *MockTopologyOps) entitiesGetLatestValues(arg0 []GroupEntityPair, arg1 []Short, arg2 uint) ([]FieldValue_v2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "entitiesGetLatestValues", arg0, arg1, arg2)
	ret0, _ := ret[0].([]FieldValue_v2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// entitiesGetLatestValues indicates an expected call of entitiesGetLatestValues.
func (mr *MockTopologyOpsMockRecorder) entitiesGetLatestValues(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "entitiesGetLatestValues", reflect.TypeOf((*MockTopologyOps)(nil).entitiesGetLatestValues), arg0, arg1, arg2)
}

// readDeviceTopology mocks base method.
func (m *MockTopologyOps) readDeviceTopology(arg0 uint) ([]P2PLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "readDeviceTopology", arg0)
	ret0, _ := ret[0].([]P2PLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// readDeviceTopology indicates an expected call of readDeviceTopology.
func (mr *MockTopologyOpsMockRecorder) readDeviceTopology(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "readDeviceTopology", reflect.TypeOf((*MockTopologyOps)(nil).readDeviceTopology), arg0)
}
