load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "topology_lib",
    srcs = ["main.go"],
    importpath = "github.com/NVIDIA/go-dcgm/samples/topology",
    visibility = ["//visibility:private"],
    deps = ["//pkg/dcgm"],
)

go_binary(
    name = "topology",
    embed = [":topology_lib"],
    visibility = ["//visibility:public"],
)
