load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "deviceInfo_lib",
    srcs = ["main.go"],
    importpath = "github.com/NVIDIA/go-dcgm/samples/deviceInfo",
    visibility = ["//visibility:private"],
    deps = ["//pkg/dcgm"],
)

go_binary(
    name = "deviceInfo",
    embed = [":deviceInfo_lib"],
    visibility = ["//visibility:public"],
)
