load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "dmon_lib",
    srcs = ["main.go"],
    importpath = "github.com/NVIDIA/go-dcgm/samples/dmon",
    visibility = ["//visibility:private"],
    deps = ["//pkg/dcgm"],
)

go_binary(
    name = "dmon",
    embed = [":dmon_lib"],
    visibility = ["//visibility:public"],
)
