load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "hostengineStatus_lib",
    srcs = ["main.go"],
    importpath = "github.com/NVIDIA/go-dcgm/samples/hostengineStatus",
    visibility = ["//visibility:private"],
    deps = ["//pkg/dcgm"],
)

go_binary(
    name = "hostengineStatus",
    embed = [":hostengineStatus_lib"],
    visibility = ["//visibility:public"],
)
